# Directories arguments

# exp_dir: "/dta/llx/yolov3/experiment-AiBox-Beijing-20220317_donot_aug/"

# change
data_dir: "/raid/lulixin/yolov3_face_detect/tf_record/Apple/"
# data_dir: "/raid/lulixin/yolov3_face_detect/tf_record/person-head-face-licensePlate/"
# exp_dir: "./experiment-AiBox-Face-20220810/"
exp_dir: "./models/experiment-AiBox-Apple-model-mbv1-0.25-20221017-num1/"
# exp_dir: "./models/experiment-AiBox-person-head-face-licensePlate-model-mbv1-0.25-20221014/"


# yolov3 arguments
img_height: 512
img_width: 512
num_channels: 3

# change
num_classes: 1
# num_classes: 4

num_object: 3
grid_height: 16
grid_width: 16
anchors: [169.54, 131.54, 228.0, 289.38, 545.15, 476.46, 43.85, 89.15, 90.62, 65.77, 86.23, 173.92, 14.62, 19.0, 23.38, 43.85, 48.23, 33.62]
random_flip: True
random_jitter_box: False
random_crop: False
random_distort_color: True

# Train arguments
max_number_of_steps: 10000
batch_size: 1
gpus: "0,1"
depth_multiplier: 0.25

# change
test_model: model.ckpt-15177

quantize: FALSE
epoch_range: 2